version: "3.4"

services:

  library_api:
    container_name: library-api
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - './backend/data:/backend/data'
    networks:
      - app_net

  library_web:
    container_name: library-web
    build: ./frontend
    links:
      - library_api
    ports:
      - "8080:8080"
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    networks:
      - app_net

networks:
  app_net:
